### ISSUE TITLE
Dead image link on doc page on Chrome

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto.io#19]
![image](https://user-images.githubusercontent.com/1105127/208869142-e5983c5a-0dd3-4e65-b2e8-3446a36da50f.png)

a simple link appears on Firefox

**Comment by Delawen** [comment]
Seems like a css problem
![imagen](https://user-images.githubusercontent.com/726590/208880160-fdb812b2-690b-4b30-9fbb-0ab2684363b3.png)

**Comment by apupier** [comment]
the problem is that the `src` of the image is `/` which obviously points to nothing
