### ISSUE TITLE
Update the Kaoto "Quick Start" page and provide more details

### ISSUE THREAD

**Issue by timothydilbert** [KaotoIO/kaoto.io#21]
* Rewrite instructions from the perspective of a newcomer
* Include instructions on how to deploy Kaoto Standalone to OpenShift/Kubernetes.

**Comment by timothydilbert** [comment]
I would like to include instructions on how to get the "Deploy" button working within a Kubernetes deployment. 

Is that feature working? And if so, is there an SME that can send through the instructions so I can include those instructions on the "Quick Start" page?

**Comment by apupier** [comment]
> Is there an SME in the Kaoto community that can send through the instructions to enable the Deploy button so that I can include those configuration steps in the instructions on the "Quick Start" page?

The deployment part has been put out of scope for the 1.0 release of Kaoto. So unfortunately, there is currently no up to date and tested information on this topic.
The general idea is to provide a very basic deploy in Kaoto codebase and to delegating with other platforms/components (Camel K, Camel JBang, various VS Code Extensions, OpenShift, Red Hat OpenShift Connector, Red Hat Smart Events, ...) the deployment.

**Comment by Delawen** [comment]
Maybe @mmelko can lend a hand here?

**Comment by Delawen** [comment]
What @timothydilbert is trying to do is to create a good tutorial on how to install Kaoto properly in a cluster.

**Comment by lhein** [comment]
You can install Kaoto using the Kaoto Operator which is available from the OperatorHub. However Kaoto itself does not support deployment to the cluster. You can however use the Camel K VS Code extension to achieve that.

**Comment by lhein** [comment]
I am closing this issue.
