### ISSUE TITLE
Standalone release are not available anymore

### ISSUE THREAD

**Issue by rodcloutier** [KaotoIO/kaoto.io#87]
Documentation still states that we can download standalone versions but they are not produced anymore.

https://github.com/KaotoIO/kaoto.io/blob/main/content/docs/quickstart.md#using-a-standalone-executable

**Comment by lordrip** [comment]
Hi @rodcloutier, thanks for reporting this issue, I'm updating the quickstart to point to the backend repository which has the binaries.

In addition to that, I would like to point out that we're working on the next version of the project and you can see it here: https://kaotoio.github.io/kaoto-next/

Here's the repository if you're interested 😃: https://github.com/KaotoIO/kaoto-next/
